In [2]:
import numpy as np

In [3]:
pred = 6/11
pblue = 5/11

In [4]:
dred = [(1,1), (1,2), (2,1), (2,2), (2,3), (4,3)]
dblue = [(-1,-1), (-1,-2), (-2,-1), (-3,-2), (-3, 1)]

In [5]:
xred = [x for x,y in dred]
yred = [y for x,y in dred]

xblue = [x for x,y in dblue]
yblue = [y for x,y in dblue]

In [6]:
miured = np.array([np.mean(xred), np.mean(yred)])
miured

array([2., 2.])

In [7]:
miublue = np.array([np.mean(xblue), np.mean(yblue)])
miublue

array([-2., -1.])

In [10]:
sigmaRed = np.cov(xred, yred)
sigmaRed

array([[1.2, 0.6],
       [0.6, 0.8]])

In [11]:
sigmaBlue = np.cov(xblue, yblue)
sigmaBlue

array([[ 1. , -0.5],
       [-0.5,  1.5]])

In [30]:
Wred = -0.5 * np.linalg.inv(sigred)
Wred

array([[-0.5 , -0.  ],
       [-0.  , -0.75]])

In [31]:
wred = np.linalg.inv(sigred).dot(miured)
wred

array([2., 3.])

In [36]:
wi0red = -0.5 * miured.T.dot(np.linalg.inv(sigred)).dot(miured) - 0.5 * np.log(np.linalg.det(sigred)) + np.log(pred)
wi0red

-5.403403249516233

In [37]:
Wblue = -0.5 * np.linalg.inv(sigblue)
Wblue

array([[-0.625     , -0.        ],
       [-0.        , -0.41666667]])

In [38]:
wblue = np.linalg.inv(sigblue).dot(miublue)
wblue

array([-2.5       , -0.83333333])

In [39]:
wi0blue = -0.5 * miublue.T.dot(np.linalg.inv(sigblue)).dot(miured) - 0.5 * np.log(np.linalg.det(sigblue)) + np.log(pblue)
wi0blue

2.5652869702291907